/** Строки интерфейса ru/en: единственный словарь подписей.
 *  Ключи типизированы, en падает в ru при пропуске — дырок в UI не бывает. */
export const STR = {
    ru: {
      newSession: 'Новая сессия',
      workspaces: 'Рабочие области',
      settings: 'Настройки',
      chat: 'Чат',
      trajectory: 'Траектория',
      terminal: 'Терминал',
      startTerminal: 'Запустить терминал',
      startingTerminal: 'Запускаю…',
      stopTerminal: 'Остановить',
      restartTerminal: 'Перезапустить',
      ptyExited: 'Процесс завершился, код',
      terminalLive: 'терминал жив',
      noTerminal: 'терминал не запущен',
      termInputPlaceholder: 'команда shell…',
      termInputLabel: 'Ввод терминала',
      searchFiles: 'поиск файлов…',
      searchNoResults: 'ничего не найдено',
      diffGit: 'Сравнить с git HEAD',
      diffNoHead: 'нет в HEAD',
      placeholder: 'сообщение модели…',
      thinking: 'думает',
      standard: 'Обычный режим',
      turns: 'ходов',
      connected: 'подключено',
      connecting: 'подключение',
      browser: 'браузер',
      modelTitle: 'Модель',
      modelRefresh: 'обновить список',
      provTab: 'Провайдеры',
      provTitle: 'Провайдеры нейросетей',
      provDesc: 'OpenAI, Claude, Kimi, DeepSeek, OpenRouter, Zen, Gemini, локальные — или свой endpoint. Ключи лежат под DPAPI.',
      provUse: 'использовать',
      provActive: 'активен',
      provFetch: 'Fetch models',
      provFetching: 'тяну модели…',
      provSave: 'сохранить',
      provCancel: 'отмена',
      provDelete: 'удалить',
      provKeyPh: 'API-ключ…',
      provKeySet: 'ключ есть',
      provKeyMissing: 'нужен ключ',
      provLocalFree: 'локальный, ключ не нужен',
      provGetKey: 'где взять ключ',
      provModelsN: 'моделей',
      provPreviewTitle: 'Найдено моделей — сохранять?',
      provSaved: 'сохранено',
      provDeleted: 'провайдер удалён',
      provActivated: 'провайдер активен',
      provCustomTitle: 'Свой провайдер',
      provNamePh: 'название…',
      provBasePh: 'https://…/v1',
      provFlavorOpenAi: 'OpenAI-совместимый',
      provFlavorAnthropic: 'Anthropic (/messages)',
      provFailed: 'не удалось',
      permTitle: 'Права',
      permAlways: 'Спрашивать всегда',
      permAlwaysDesc: 'Подтверждение на каждый вызов инструмента',
      permDangerous: 'Только опасные',
      permDangerousDesc: 'bash, pwsh, write, edit, delete — с подтверждением',
      permNever: 'Никогда не спрашивать',
      permNeverDesc: 'Опасно: модель действует без подтверждений',
      permApplied: 'права применены',
      permFailed: 'не удалось применить права',
      securityTab: 'Безопасность',
      dpapiTitle: 'API-ключ под DPAPI',
      dpapiDesc: 'Ключ шифруется под учётной записью Windows и лежит в базе. .env остаётся в приоритете.',
      dpapiSave: 'Зашифровать',
      dpapiForget: 'Забыть',
      dpapiStored: 'ключ сохранён под DPAPI',
      dpapiNotStored: 'DPAPI-ключ не задан',
      dpapiSaved: 'ключ зашифрован и сохранён',
      dpapiCleared: 'DPAPI-ключ удалён',
      dpapiFailed: 'не удалось',
      httpApiTitle: 'Локальный HTTP API',
      httpApiOn: 'Слушает',
      httpApiOff: 'Выключен — задайте SWAGCOD_HTTP_PORT или pref http_api_port и перезапустите',
      httpApiCopy: 'Копировать токен',
      httpApiCopied: 'токен скопирован',
      httpApiCopyFail: 'не удалось скопировать',
      telemetryTab: 'Телеметрия',
      telemetryTokens: 'Токены/день — 30 дней, UTC',
      telemetryLatency: 'Латентность провайдера — 24 ч, мс до первого события',
      telemetryLag: 'Лаги шины — 24 ч, дельта за минуту (синий — события, красный — потери)',
      telemetryTasks: 'Фоновые задачи',
      telemetryEmpty: 'Данных пока нет',
      telemetryRefresh: 'Обновить',
      taskColState: 'состояние',
      taskColAttempts: 'попытки',
      taskColNext: 'следующий',
      taskColLog: 'журнал',
      taskCancel: 'отменить',
      updateTitle: 'Обновления',
      updateIdle: 'Новые версии приходят с GitHub Releases',
      updateVersion: 'Версия',
      updateCheckBtn: 'Проверить',
      updateChecking: 'Проверяю…',
      updateUpToDate: 'У вас последняя версия',
      updateAvailable: 'Доступна новая версия',
      updateInstallBtn: 'Скачать и установить',
      updateDownloading: 'Загрузка',
      updateReady: 'Установлено — нужен перезапуск',
      updateRestartBtn: 'Перезапустить сейчас',
      updateError: 'Ошибка проверки',
      palGroupSession: 'Сессии',
      palGroupExport: 'Экспорт',
      palGroupAgent: 'Агент',
      palGroupView: 'Вид',
      palGroupDev: 'Разработка',
      palPlaceholder: 'команда…',
      palEmpty: 'ничего не найдено',
      cmdNewDesc: 'новая сессия',
      cmdClearDesc: 'очистить транскрипцию текущей сессии',
      cmdCompactDesc: 'свернуть старые ходы в сводку (B-3)',
      cmdCompactDone: 'сжато старых сообщений',
      cmdCompactNothing: 'сжимать нечего: история ещё мала',
      cmdExportDesc: 'журнал сессии в markdown',
      cmdDiagDesc: 'диагностика в файл',
      cmdModelDesc: 'выбрать модель ответа',
      cmdPermAlwaysDesc: 'права: спрашивать всегда',
      cmdPermDangerousDesc: 'права: только опасные',
      cmdPermNeverDesc: 'права: никогда не спрашивать',
      cmdUpdateDesc: 'проверить обновления с GitHub Releases',
      cmdTasksDesc: 'телеметрия фоновых задач',
      cmdThemeDarkDesc: 'тёмная тема',
      cmdThemeLightDesc: 'светлая тема',
      cmdThemeContrastDesc: 'контрастная тема',
      cmdThemeSystemDesc: 'тема из системы',
      cmdZoomInDesc: 'крупнее (Ctrl++)',
      cmdZoomOutDesc: 'мельче (Ctrl+-)',
      cmdZoomResetDesc: 'сброс масштаба (Ctrl+0)',
      cmdSidebarDesc: 'свернуть или развернуть боковую панель',
      cmdFxDesc: 'эффекты фона вкл/выкл',
      cmdBgMatrixDesc: 'фон: matrix rain',
      cmdBgSphereDesc: 'фон: wireframe sphere',
      cmdSim50Desc: 'симуляция стрима: 50 токенов',
      cmdSim2kDesc: 'симуляция стрима: 2k токенов',
      cmdSim20kDesc: 'симуляция стрима: 20k токенов',
      sessPolicyTitle: 'Права этой сессии',
      sessPolicyDesc: 'Переопределяет глобальную политику подтверждений для открытой сессии.',
      policyGlobal: 'как глобальные',
      cmdRulesTitle: 'Списки команд (allow/deny)',
      cmdRulesDesc:
        'Порядок: deny → allow → политика подтверждений. Deny отклоняет вызов без диалога, allow исполняет без диалога. По одному regex на строку, регистр не важен, «#» — комментарий.',
      cmdAllowLabel: 'Разрешить без диалога',
      cmdDenyLabel: 'Запретить всегда',
      cmdAllowHint: 'read-only команды: git status, cargo test…',
      cmdDenyHint: 'необратимое: rm -rf /, format, shutdown, pipe в оболочку…',
      cmdRulesSave: 'Сохранить',
      cmdRulesBusy: 'Сохраняю…',
      cmdRulesReset: 'Дефолты',
      cmdRulesSaved: 'Сохранено: правил {n}',
      cmdRulesEmpty: 'Сохранено: правил нет — решает политика',
      approvalLogTitle: 'Журнал подтверждений',
      approvalLogBtn: 'Обновить',
      approvalLogEmpty: 'записей нет',
      logColTime: 'когда',
      logColTool: 'инструмент',
      logColDecision: 'решение',
      logColActor: 'кто',
      decisionApproved: 'одобрено',
      decisionDenied: 'отклонено',
      actorUser: 'человек',
      actorSystem: 'система',
      quietTurn: 'подозрительно тихо',
    attachTitle: 'Прикрепить файл',
      dshImportTitle: 'Импорт сессий из DSH',
      dshImportDesc: 'Перенести историю DSH Desktop в SwagCod; повтор не дублирует',
      dshImportRun: 'Импортировать',
      dshImportBusy: 'Импортирую…',
      dshImportDone: 'Перенесено сессий: {s}, ходов: {t}, сообщений: {m}',
      dshImportResumed: 'догружено',
      dshImportSkipped: 'пропущено',
      dshImportErrors: 'ошибок',
      dshImportNone: 'DSH-сессий не найдено (или все уже перенесены)',
      mcpTitle: 'MCP-серверы',
      mcpDesc: 'Внешние инструменты по Model Context Protocol (stdio). Команда с аргументами через пробел.',
      mcpToolsWord: 'инстр.',
      mcpRemove: 'Убрать',
      mcpNamePh: 'имя',
      mcpCommandPh: 'команда с аргументами',
      mcpAdd: 'Добавить',
      mcpBusy: 'Подключаю…',
      mcpNeedBoth: 'Нужны имя и команда',
      jsPlugTitle: 'JS-плагины',
      jsPlugReload: 'Перезагрузить',
      jsPlugBusy: 'Перезагружаю…',
      jsPlugNone: 'В каталоге plugins нет .js-плагинов. Файл плагина вызывает swagcod.define({ name, description, parameters, handler }).',
      approvalTitle: 'Подтверждение действия',
      approvalHint: 'Агент просит выполнить опасный инструмент. Команда и аргументы показаны полностью.',
      approve: 'Подтвердить',
      deny: 'Отклонить',
      appearance: 'Тема',
      dark: 'Тёмная',
      light: 'Светлая',
      contrast: 'Контрастная',
      system: 'Системная',
      fontSize: 'Размер шрифта',
      fontSizeDesc: 'Текст сообщений в транскрипции',
      zoom: 'Масштаб интерфейса',
      zoomDesc: 'Растягивает всё окно: панели, шрифт, отступы',
      sidebarWidth: 'Ширина панели',
      language: 'Язык',
      maximize: 'Развернуть на весь экран',
      restore: 'Вернуть панель',
      reset: 'Сброс',
      ctx: 'контекст',
      speedFast: 'быстрая',
      speedBalanced: 'средняя',
      speedHeavy: 'тяжёлая',
      capTools: 'инструменты',
      capReasoning: 'рассуждения',
      capVision: 'зрение',
      noModels: 'Список моделей не получен — проверь .env и провайдера',
      openModelSettings: 'Настройки моделей',
      tempAuto: 'temperature',
      tempAutoDesc: 'Не переопределяем: провайдер применяет своё значение по умолчанию',
      auto: 'авто',
      studioAccent: 'Свой акцент',
      studioAccentDesc: 'Круглая палитра: перекрашивает кнопки, свечения и декор',
      studioTint: 'Тонировка',
      studioTintDesc: 'Мягкий цветовой слой поверх всего интерфейса',
      studioMedia: 'Медиафон',
      studioMediaDesc: 'gif, mp4, webm или картинка на задний план',
      studioMediaPick: 'выбрать файл',
      studioMediaClear: 'убрать',
      studioMediaBusy: 'сохраняю файл…',
      wsTitle: 'Пути рабочих областей',
      wsEmpty: 'Нет открытых областей',
      wsOpen: 'открыть в проводнике',
      wsCopy: 'копировать путь',
      stopTitle: 'остановить нейронку',
      send: 'отправить',
      queueTitle: 'в очереди',
      searchModels: 'фильтр моделей…',
      currentModel: 'текущая',
      trajectoryTitle: 'Ходы и инструменты',
      noTurns: 'Нет ходов — отправьте сообщение модели',
      turn: 'Ход',
      subagentTurn: 'Суб-агент',
      events: 'событий',
      glowTitle: 'Свечение',
      glowDesc: 'Сила акцентных теней и подсветок интерфейса',
      glowSoft: 'мягкое',
      glowNormal: 'обычное',
      glowStrong: 'сильное',
      browse: 'обзор…',
      zoomHotkeys: 'Масштаб всего окна; горячие клавиши Ctrl++ / Ctrl+- / Ctrl+0',
      chatCreating: 'чат создаётся…',
      collapseSidebar: 'свернуть боковую панель',
      filterSessions: 'поиск сессий',
      filterPlaceholder: 'фильтр сессий…',
      groupOrder: 'группировка и порядок',
      groupBy: 'группировать по',
      groupWs: 'рабочим папкам',
      groupList: 'единым списком',
      orderBy: 'порядок',
      orderManual: 'вручную',
      orderUpdated: 'по обновлению',
      openFolder: 'открыть папку сессии',
      downloadLog: 'скачать журнал сессии',
      copyId: 'копировать id сессии',
      more: 'ещё действия',
      filesPanel: 'файлы папки чата',
      tabAdd: 'добавить файл вкладкой',
      closeFiles: 'закрыть панель файлов',
      noSession: 'нет открытой сессии',
      minimize: 'свернуть окно',
      closeWin: 'закрыть окно',
      searchTranscript: 'поиск по транскрипции',
      sessionFolder: 'папка и журнал сессии',
    },
    en: {
      newSession: 'New Session',
      workspaces: 'Workspaces',
      settings: 'Settings',
      chat: 'Chat',
      trajectory: 'Trajectory',
      terminal: 'Terminal',
      startTerminal: 'Start terminal',
      startingTerminal: 'Starting…',
      stopTerminal: 'Stop',
      restartTerminal: 'Restart',
      ptyExited: 'Process exited with code',
      terminalLive: 'terminal live',
      noTerminal: 'terminal not running',
      termInputPlaceholder: 'shell command…',
      termInputLabel: 'Terminal input',
      searchFiles: 'search files…',
      searchNoResults: 'nothing found',
      diffGit: 'Compare against git HEAD',
      diffNoHead: 'not in HEAD',
      placeholder: 'message the model…',
      thinking: 'thinking',
      standard: 'Standard mode',
      turns: 'turns',
      connected: 'connected',
      connecting: 'connecting',
      browser: 'browser',
      modelTitle: 'Model',
      modelRefresh: 'refresh list',
      provTab: 'Providers',
      provTitle: 'AI providers',
      provDesc: 'OpenAI, Claude, Kimi, DeepSeek, OpenRouter, Zen, Gemini, local ones — or your own endpoint. Keys live under DPAPI.',
      provUse: 'use',
      provActive: 'active',
      provFetch: 'Fetch models',
      provFetching: 'fetching models…',
      provSave: 'save',
      provCancel: 'cancel',
      provDelete: 'delete',
      provKeyPh: 'API key…',
      provKeySet: 'key set',
      provKeyMissing: 'key required',
      provLocalFree: 'local, no key needed',
      provGetKey: 'where to get a key',
      provModelsN: 'models',
      provPreviewTitle: 'Models found — save?',
      provSaved: 'saved',
      provDeleted: 'provider deleted',
      provActivated: 'provider active',
      provCustomTitle: 'Custom provider',
      provNamePh: 'name…',
      provBasePh: 'https://…/v1',
      provFlavorOpenAi: 'OpenAI-compatible',
      provFlavorAnthropic: 'Anthropic (/messages)',
      provFailed: 'failed',
      permTitle: 'Permissions',
      permAlways: 'Ask every time',
      permAlwaysDesc: 'Confirm each tool call',
      permDangerous: 'Dangerous only',
      permDangerousDesc: 'bash, pwsh, write, edit, delete need approval',
      permNever: 'Never ask',
      permNeverDesc: 'Dangerous: the model acts without approval',
      permApplied: 'permissions applied',
      permFailed: 'failed to apply permissions',
      securityTab: 'Security',
      dpapiTitle: 'API key under DPAPI',
      dpapiDesc: 'The key is encrypted under your Windows account and stored in the DB. .env stays priority.',
      dpapiSave: 'Encrypt',
      dpapiForget: 'Forget',
      dpapiStored: 'key stored under DPAPI',
      dpapiNotStored: 'no DPAPI key set',
      dpapiSaved: 'key encrypted and saved',
      dpapiCleared: 'DPAPI key removed',
      dpapiFailed: 'failed',
      httpApiTitle: 'Local HTTP API',
      httpApiOn: 'Listening on',
      httpApiOff: 'Off — set SWAGCOD_HTTP_PORT or pref http_api_port and restart',
      httpApiCopy: 'Copy token',
      httpApiCopied: 'token copied',
      httpApiCopyFail: 'copy failed',
      telemetryTab: 'Telemetry',
      telemetryTokens: 'Tokens/day — 30 days, UTC',
      telemetryLatency: 'Provider latency — 24 h, ms to first event',
      telemetryLag: 'Bus lag — 24 h, per-minute deltas (blue events, red drops)',
      telemetryTasks: 'Background tasks',
      telemetryEmpty: 'No data yet',
      telemetryRefresh: 'Refresh',
      taskColState: 'state',
      taskColAttempts: 'attempts',
      taskColNext: 'next',
      taskColLog: 'log',
      taskCancel: 'cancel',
      updateTitle: 'Updates',
      updateIdle: 'New versions arrive from GitHub Releases',
      updateVersion: 'Version',
      updateCheckBtn: 'Check',
      updateChecking: 'Checking…',
      updateUpToDate: 'You are on the latest version',
      updateAvailable: 'New version available',
      updateInstallBtn: 'Download & install',
      updateDownloading: 'Downloading',
      updateReady: 'Installed — restart required',
      updateRestartBtn: 'Restart now',
      updateError: 'Check failed',
      palGroupSession: 'Sessions',
      palGroupExport: 'Export',
      palGroupAgent: 'Agent',
      palGroupView: 'View',
      palGroupDev: 'Dev',
      palPlaceholder: 'command…',
      palEmpty: 'nothing found',
      cmdNewDesc: 'new session',
      cmdClearDesc: 'clear current session transcript',
      cmdCompactDesc: 'fold older turns into a summary (B-3)',
      cmdCompactDone: 'old messages folded',
      cmdCompactNothing: 'nothing to compact: history is still small',
      cmdExportDesc: 'session log to markdown',
      cmdDiagDesc: 'diagnostics to file',
      cmdModelDesc: 'pick the answer model',
      cmdPermAlwaysDesc: 'permissions: always ask',
      cmdPermDangerousDesc: 'permissions: dangerous only',
      cmdPermNeverDesc: 'permissions: never ask',
      cmdUpdateDesc: 'check updates from GitHub Releases',
      cmdTasksDesc: 'background tasks telemetry',
      cmdThemeDarkDesc: 'dark theme',
      cmdThemeLightDesc: 'light theme',
      cmdThemeContrastDesc: 'contrast theme',
      cmdThemeSystemDesc: 'system theme',
      cmdZoomInDesc: 'zoom in (Ctrl++)',
      cmdZoomOutDesc: 'zoom out (Ctrl+-)',
      cmdZoomResetDesc: 'reset zoom (Ctrl+0)',
      cmdSidebarDesc: 'collapse or expand the sidebar',
      cmdFxDesc: 'background effects on/off',
      cmdBgMatrixDesc: 'background: matrix rain',
      cmdBgSphereDesc: 'background: wireframe sphere',
      cmdSim50Desc: 'stream simulation: 50 tokens',
      cmdSim2kDesc: 'stream simulation: 2k tokens',
      cmdSim20kDesc: 'stream simulation: 20k tokens',
      sessPolicyTitle: 'This session permissions',
      sessPolicyDesc: 'Overrides the global approval policy for the open session.',
      policyGlobal: 'inherit global',
      cmdRulesTitle: 'Command lists (allow/deny)',
      cmdRulesDesc:
        'Order: deny → allow → approval policy. Deny rejects a call without a dialog, allow runs it without a dialog. One regex per line, case-insensitive, «#» starts a comment.',
      cmdAllowLabel: 'Allow without dialog',
      cmdDenyLabel: 'Deny always',
      cmdAllowHint: 'read-only commands: git status, cargo test…',
      cmdDenyHint: 'irreversible: rm -rf /, format, shutdown, pipe into a shell…',
      cmdRulesSave: 'Save',
      cmdRulesBusy: 'Saving…',
      cmdRulesReset: 'Defaults',
      cmdRulesSaved: 'Saved: {n} rules',
      cmdRulesEmpty: 'Saved: no rules — the policy decides',
      approvalLogTitle: 'Approval journal',
      approvalLogBtn: 'Refresh',
      approvalLogEmpty: 'no entries',
      logColTime: 'when',
      logColTool: 'tool',
      logColDecision: 'decision',
      logColActor: 'who',
      decisionApproved: 'approved',
      decisionDenied: 'denied',
      actorUser: 'user',
      actorSystem: 'system',
      quietTurn: 'suspiciously quiet',
    attachTitle: 'Attach file',
      dshImportTitle: 'Import DSH sessions',
      dshImportDesc: 'Move DSH Desktop history into SwagCod; re-import does not duplicate',
      dshImportRun: 'Import',
      dshImportBusy: 'Importing…',
      dshImportDone: 'Imported sessions: {s}, turns: {t}, messages: {m}',
      dshImportResumed: 'resumed',
      dshImportSkipped: 'skipped',
      dshImportErrors: 'errors',
      dshImportNone: 'No DSH sessions found (or all already imported)',
      mcpTitle: 'MCP servers',
      mcpDesc: 'External tools via Model Context Protocol (stdio). Command with args, space-separated.',
      mcpToolsWord: 'tools',
      mcpRemove: 'Remove',
      mcpNamePh: 'name',
      mcpCommandPh: 'command with args',
      mcpAdd: 'Add',
      mcpBusy: 'Connecting…',
      mcpNeedBoth: 'Name and command are required',
      jsPlugTitle: 'JS plugins',
      jsPlugReload: 'Reload',
      jsPlugBusy: 'Reloading…',
      jsPlugNone: 'No .js plugins in the plugins directory. A plugin file must call swagcod.define({ name, description, parameters, handler }).',
      approvalTitle: 'Approve action',
      approvalHint: 'The agent wants to run a dangerous tool. Command and arguments are shown in full.',
      approve: 'Approve',
      deny: 'Deny',
      appearance: 'Appearance',
      dark: 'Dark',
      light: 'Light',
      contrast: 'Contrast',
      system: 'System',
      fontSize: 'Font size',
      fontSizeDesc: 'Conversation text in the transcript',
      zoom: 'UI zoom',
      zoomDesc: 'Scales the whole window: panels, text, spacing',
      sidebarWidth: 'Sidebar width',
      language: 'Language',
      maximize: 'Maximize to full screen',
      restore: 'Restore sidebar',
      reset: 'Reset',
      ctx: 'context',
      speedFast: 'fast',
      speedBalanced: 'balanced',
      speedHeavy: 'heavy',
      capTools: 'tools',
      capReasoning: 'reasoning',
      capVision: 'vision',
      noModels: 'Model list unavailable — check .env and the provider',
      openModelSettings: 'Model settings',
      tempAuto: 'temperature',
      tempAutoDesc: 'Not overridden: the provider applies its own default',
      auto: 'auto',
      studioAccent: 'Custom accent',
      studioAccentDesc: 'Round palette: recolors buttons, glows and decor',
      studioTint: 'Color tint',
      studioTintDesc: 'Soft color layer over the whole interface',
      studioMedia: 'Background media',
      studioMediaDesc: 'gif, mp4, webm or an image behind the UI',
      studioMediaPick: 'pick file',
      studioMediaClear: 'remove',
      studioMediaBusy: 'saving file…',
      wsTitle: 'Workspace paths',
      wsEmpty: 'No workspaces yet',
      wsOpen: 'open in explorer',
      wsCopy: 'copy path',
      stopTitle: 'stop the model',
      send: 'send',
      queueTitle: 'queued',
      searchModels: 'filter models…',
      currentModel: 'current',
      trajectoryTitle: 'Turns and tools',
      noTurns: 'No turns yet — send a message to the model',
      turn: 'Turn',
      subagentTurn: 'Sub-agent',
      events: 'events',
      glowTitle: 'Glow',
      glowDesc: 'Strength of accent shadows and highlights',
      glowSoft: 'soft',
      glowNormal: 'normal',
      glowStrong: 'strong',
      browse: 'browse…',
      zoomHotkeys: 'Scales the whole window; hotkeys Ctrl++ / Ctrl+- / Ctrl+0',
      chatCreating: 'chat is being created…',
      collapseSidebar: 'collapse sidebar',
      filterSessions: 'search sessions',
      filterPlaceholder: 'filter sessions…',
      groupOrder: 'grouping and order',
      groupBy: 'group by',
      groupWs: 'workspace',
      groupList: 'single list',
      orderBy: 'order by',
      orderManual: 'manual',
      orderUpdated: 'last updated',
      openFolder: 'open session folder',
      downloadLog: 'download session log',
      copyId: 'copy session id',
      more: 'more actions',
      filesPanel: 'chat folder files',
      tabAdd: 'add file as tab',
      closeFiles: 'close files panel',
      noSession: 'no open session',
      minimize: 'minimize window',
      closeWin: 'close window',
      searchTranscript: 'search transcript',
      sessionFolder: 'session folder and log',
    },
  } as const

export type StrKey = keyof (typeof STR)['ru']

/** Перевод с фолбэком: en -> ru -> сам ключ. */
export function translate(lang: 'ru' | 'en', key: StrKey): string {
  return STR[lang][key] ?? STR.ru[key] ?? String(key)
}
