/** Строки интерфейса ru/en: единственный словарь подписей.
 *  Ключи типизированы, en падает в ru при пропуске — дырок в UI не бывает. */
export const STR = {
    ru: {
      newSession: 'Новая сессия',
      workspaces: 'Рабочие области',
      settings: 'Настройки',
      chat: 'Чат',
      trajectory: 'Траектория',
      placeholder: 'сообщение модели…',
      thinking: 'думает',
      standard: 'Обычный режим',
      turns: 'ходов',
      connected: 'подключено',
      connecting: 'подключение',
      browser: 'браузер',
      modelTitle: 'Модель',
      permTitle: 'Права',
      permAlways: 'Спрашивать всегда',
      permAlwaysDesc: 'Подтверждение на каждый вызов инструмента',
      permDangerous: 'Только опасные',
      permDangerousDesc: 'bash, pwsh, write, edit, delete — с подтверждением',
      permNever: 'Никогда не спрашивать',
      permNeverDesc: 'Опасно: модель действует без подтверждений',
      permApplied: 'права применены',
      permFailed: 'не удалось применить права',
      approvalTitle: 'Подтверждение действия',
      approvalHint: 'Агент просит выполнить опасный инструмент. Команда и аргументы показаны полностью.',
      approve: 'Подтвердить',
      deny: 'Отклонить',
      appearance: 'Тема',
      dark: 'Тёмная',
      light: 'Светлая',
      contrast: 'Контрастная',
      system: 'Системная',
      fontSize: 'Размер шрифта',
      fontSizeDesc: 'Текст сообщений в транскрипции',
      zoom: 'Масштаб интерфейса',
      zoomDesc: 'Растягивает всё окно: панели, шрифт, отступы',
      sidebarWidth: 'Ширина панели',
      language: 'Язык',
      maximize: 'Развернуть на весь экран',
      restore: 'Вернуть панель',
      reset: 'Сброс',
      ctx: 'контекст',
      speedFast: 'быстрая',
      speedBalanced: 'средняя',
      speedHeavy: 'тяжёлая',
      capTools: 'инструменты',
      capReasoning: 'рассуждения',
      capVision: 'зрение',
      noModels: 'Список моделей не получен — проверь .env и провайдера',
      openModelSettings: 'Настройки моделей',
      tempAuto: 'temperature',
      tempAutoDesc: 'Не переопределяем: провайдер применяет своё значение по умолчанию',
      auto: 'авто',
      studioAccent: 'Свой акцент',
      studioAccentDesc: 'Круглая палитра: перекрашивает кнопки, свечения и декор',
      studioTint: 'Тонировка',
      studioTintDesc: 'Мягкий цветовой слой поверх всего интерфейса',
      studioMedia: 'Медиафон',
      studioMediaDesc: 'gif, mp4, webm или картинка на задний план',
      studioMediaPick: 'выбрать файл',
      studioMediaClear: 'убрать',
      studioMediaBusy: 'сохраняю файл…',
      wsTitle: 'Пути рабочих областей',
      wsEmpty: 'Нет открытых областей',
      wsOpen: 'открыть в проводнике',
      wsCopy: 'копировать путь',
      stopTitle: 'остановить нейронку',
      send: 'отправить',
      queueTitle: 'в очереди',
      searchModels: 'фильтр моделей…',
      currentModel: 'текущая',
      trajectoryTitle: 'Ходы и инструменты',
      noTurns: 'Нет ходов — отправьте сообщение модели',
      turn: 'Ход',
      events: 'событий',
    },
    en: {
      newSession: 'New Session',
      workspaces: 'Workspaces',
      settings: 'Settings',
      chat: 'Chat',
      trajectory: 'Trajectory',
      placeholder: 'message the model…',
      thinking: 'thinking',
      standard: 'Standard mode',
      turns: 'turns',
      connected: 'connected',
      connecting: 'connecting',
      browser: 'browser',
      modelTitle: 'Model',
      permTitle: 'Permissions',
      permAlways: 'Ask every time',
      permAlwaysDesc: 'Confirm each tool call',
      permDangerous: 'Dangerous only',
      permDangerousDesc: 'bash, pwsh, write, edit, delete need approval',
      permNever: 'Never ask',
      permNeverDesc: 'Dangerous: the model acts without approval',
      permApplied: 'permissions applied',
      permFailed: 'failed to apply permissions',
      approvalTitle: 'Approve action',
      approvalHint: 'The agent wants to run a dangerous tool. Command and arguments are shown in full.',
      approve: 'Approve',
      deny: 'Deny',
      appearance: 'Appearance',
      dark: 'Dark',
      light: 'Light',
      contrast: 'Contrast',
      system: 'System',
      fontSize: 'Font size',
      fontSizeDesc: 'Conversation text in the transcript',
      zoom: 'UI zoom',
      zoomDesc: 'Scales the whole window: panels, text, spacing',
      sidebarWidth: 'Sidebar width',
      language: 'Language',
      maximize: 'Maximize to full screen',
      restore: 'Restore sidebar',
      reset: 'Reset',
      ctx: 'context',
      speedFast: 'fast',
      speedBalanced: 'balanced',
      speedHeavy: 'heavy',
      capTools: 'tools',
      capReasoning: 'reasoning',
      capVision: 'vision',
      noModels: 'Model list unavailable — check .env and the provider',
      openModelSettings: 'Model settings',
      tempAuto: 'temperature',
      tempAutoDesc: 'Not overridden: the provider applies its own default',
      auto: 'auto',
      studioAccent: 'Custom accent',
      studioAccentDesc: 'Round palette: recolors buttons, glows and decor',
      studioTint: 'Color tint',
      studioTintDesc: 'Soft color layer over the whole interface',
      studioMedia: 'Background media',
      studioMediaDesc: 'gif, mp4, webm or an image behind the UI',
      studioMediaPick: 'pick file',
      studioMediaClear: 'remove',
      studioMediaBusy: 'saving file…',
      wsTitle: 'Workspace paths',
      wsEmpty: 'No workspaces yet',
      wsOpen: 'open in explorer',
      wsCopy: 'copy path',
      stopTitle: 'stop the model',
      send: 'send',
      queueTitle: 'queued',
      searchModels: 'filter models…',
      currentModel: 'current',
      trajectoryTitle: 'Turns and tools',
      noTurns: 'No turns yet — send a message to the model',
      turn: 'Turn',
      events: 'events',
    },
  } as const

export type StrKey = keyof (typeof STR)['ru']

/** Перевод с фолбэком: en -> ru -> сам ключ. */
export function translate(lang: 'ru' | 'en', key: StrKey): string {
  return STR[lang][key] ?? STR.ru[key] ?? String(key)
}
